//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.11 at 04:54:39 PM IST 
//


package com.example.spring.soap.api.calculator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="secondNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="addition" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="subtraction" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="multiplication" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="division" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="scenarioType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logId",
    "firstNumber",
    "secondNumber",
    "addition",
    "subtraction",
    "multiplication",
    "division",
    "scenarioType"
})
@XmlRootElement(name = "CalculatorResponse")
public class CalculatorResponse {

    @XmlElement(required = true)
    protected String logId;
    protected int firstNumber;
    protected int secondNumber;
    protected int addition;
    protected int subtraction;
    protected int multiplication;
    protected int division;
    @XmlElement(required = true)
    protected String scenarioType;

    /**
     * Gets the value of the logId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogId() {
        return logId;
    }

    /**
     * Sets the value of the logId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogId(String value) {
        this.logId = value;
    }

    /**
     * Gets the value of the firstNumber property.
     * 
     */
    public int getFirstNumber() {
        return firstNumber;
    }

    /**
     * Sets the value of the firstNumber property.
     * 
     */
    public void setFirstNumber(int value) {
        this.firstNumber = value;
    }

    /**
     * Gets the value of the secondNumber property.
     * 
     */
    public int getSecondNumber() {
        return secondNumber;
    }

    /**
     * Sets the value of the secondNumber property.
     * 
     */
    public void setSecondNumber(int value) {
        this.secondNumber = value;
    }

    /**
     * Gets the value of the addition property.
     * 
     */
    public int getAddition() {
        return addition;
    }

    /**
     * Sets the value of the addition property.
     * 
     */
    public void setAddition(int value) {
        this.addition = value;
    }

    /**
     * Gets the value of the subtraction property.
     * 
     */
    public int getSubtraction() {
        return subtraction;
    }

    /**
     * Sets the value of the subtraction property.
     * 
     */
    public void setSubtraction(int value) {
        this.subtraction = value;
    }

    /**
     * Gets the value of the multiplication property.
     * 
     */
    public int getMultiplication() {
        return multiplication;
    }

    /**
     * Sets the value of the multiplication property.
     * 
     */
    public void setMultiplication(int value) {
        this.multiplication = value;
    }

    /**
     * Gets the value of the division property.
     * 
     */
    public int getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     */
    public void setDivision(int value) {
        this.division = value;
    }

    /**
     * Gets the value of the scenarioType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenarioType() {
        return scenarioType;
    }

    /**
     * Sets the value of the scenarioType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenarioType(String value) {
        this.scenarioType = value;
    }

}
